# Generated by Django 3.0.9 on 2020-08-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.BigIntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
